<h1>User Registration</h1>
<form action="<?=$this->url('usuarios',['action'=>'save'])?>" method="post">
Nome :
<input type="text" autofocus="autofocus" name="nome" value="<?=$this->usuario->nome?>">
<br/>
<select name="codigo_perfil">
<?=$this->partialLoop('perfis_usuario.phtml',$this->perfis)?>
</select>
<input type="hidden" value="<?=$this->usuario->codigo?>" name="codigo">
<input type="submit" value="gravar">
</form>
<a href="<?=$this->url('usuarios')?>">Back</a>
