<h1><?=$this->translate('User Registration')?></h1>
<form action="<?=$this->url('usuarios',['action'=>'save'])?>" method="post">
<?=$this->translate('Name')?>:
<input type="text" autofocus="autofocus" name="nome" value="<?=$this->usuario->nome?>">
<br/>
<select name="codigo_perfil">
<?=$this->partialLoop('perfis_usuario.phtml',$this->perfis)?>
</select>
<input type="hidden" value="<?=$this->usuario->codigo?>" name="codigo">
<input type="submit" value="<?=$this->translate('save')?>">
</form>
<a href="<?=$this->url('usuarios')?>"><?=$this->translate('Go back')?></a>
