<h1>Cadastro de Permissoes_perfil</h1>
<form action="<?=$this->url('permissoes_perfil',['action'=>'save'])?>" method="post">
<select name="codigo_perfil">
<?=$this->partialLoop('perfis_permissoes_perfil.phtml',$this->perfis)?>
</select>
<select name="codigo_permissao">
<?=$this->partialLoop('permissoes_permissoes_perfil.phtml',$this->permissoes)?>
</select>
<input type="hidden" value="<?=$this->grade->codigo?>" name="codigo">
<input type="submit" value="gravar">
</form>
<a href="<?=$this->url('permissoes_perfil')?>">Voltar</a>
