<a href="<?=$this->url('participantes',['action'=>'edit'])?>"><?=$this->translate('Add participants')?></a>
<table>
<thead>
<tr>
<th><?=$this->translate('Code')?></th>
<th><?=$this->translate('User')?></th>
<th><?=$this->translate('Email')?></th>
<th><?=$this->translate('Name')?></th>
<th><?=$this->translate('City')?></th>
<th><?=$this->translate('Telephone')?></th>
<th><?=$this->translate('Organization')?></th>
<th><?=$this->translate('Cpf')?></th>
<th><?=$this->translate('Passport')?></th>
<th><?=$this->translate('Speaker')?></th>
</tr>
</thead>
<tbody>
<?=$this->partialLoop('participantes.phtml',$this->participantes)?>
</tbody>
</table>
<a href="<?=$this->url('application',['action' => 'event-control'])?>"><?=$this->translate('Event Management')?></a>