<a href="<?=$this->url('categorias',['action'=>'edit'])?>"><?=$this->translate('Add Category')?></a>
<table>
<thead>
<tr>
<th><?=$this->translate('Code')?></th>
<th><?=$this->translate('Name')?></th>
</tr>
</thead>
<tbody>
<?=$this->partialLoop('categorias.phtml',$this->categorias)?>
</tbody>
</table>
<a href="<?=$this->url('application',['action' => 'event-control'])?>"><?=$this->translate('Event Management')?></a>