<h1><?=$this->translate('Permission for a Profile Registration')?></h1>
<form action="<?=$this->url('permissoesperfis',['action'=>'save'])?>" method="post">
<select name="codigo_perfil">
<?=$this->partialLoop('perfis-permissoes-perfis.phtml',$this->perfis)?>
</select>
<select name="codigo_permissao">
<?=$this->partialLoop('permissoes-permissoes-perfis.phtml',$this->permissoes)?>
</select>
<input type="hidden" value="<?=$this->grade->codigo?>" name="codigo">
<input type="submit" value="<?=$this->translate('save')?>">
</form>
<a href="<?=$this->url('permissoesperfis')?>"><?=$this->translate('Go back')?></a>
