<a href="<?=$this->url('permissoesperfis',['action'=>'edit'])?>"><?=$this->translate('Add permission for a profile')?></a>
<table>
<thead>
<tr>
<th><?=$this->translate('Perfil')?></th>
<th><?=$this->translate('Permission')?></th>
</tr>
</thead>
<tbody>
<?=$this->partialLoop('permissoes-perfis.phtml',$this->permissoesperfis)?>
</tbody>
</table>
<a href="<?=$this->url('application',['action'=>'access-control'])?>"><?=$this->translate('Go back')?></a>