<section class="panel grey darken-4">
    <div class="container grey lighten-3" style="height: 64px">
        <div class="row"></div>
    </div>
</section>

<section class="panel grey darken-4">
    <div class="container grey lighten-3" style="padding-bottom: 30px">
        <div class="container">
            <div class="row">
                <div class="sm-font blue-grey-text">
                    <span style="display: inline-block;">O evento</span>
                </div>
            </div>
            <div class="row" style="margin-bottom: 0">
                <div>

                    <section class="panel grey lighten-5">
                        <div class="container valign-wrapper">
                            <div class="row">
                                <div class="col">
                                    <div class="left-align lg-padding-v">
                                        <span class="xs-font blue-text text-darken-4">Fórum de
                                            Tecnologia em Software Livre</span><br> <span
                                            class="xxs-font grey-text text-darken-4">
                                            <p>O Fórum de Tecnologia em Software Livre, FTSL, é um evento
                                                anual, realizado em Curitiba/PR, sendo considerado o maior
                                                evento gratuito de Software Livre do país, e tem como
                                                propósito a disseminação de novas tecnologias baseadas em
                                                Software Livre, bem como, a troca de experiências com as
                                                comunidades, universidades e empresas públicas e privadas,
                                                por meio de palestras, painéis/mesas-redondas e
                                                oficinas/minicursos.</p>
                                            <p>
                                                <span style="color: #0D47A1; font-weight: bold">Local de
                                                    realização:</span> Universidade Tecnológica Federal do
                                                Paraná. Av. Sete de Setembro, 3165.
                                            </p>
                                            <p>As atividades da programação estarão divididas em:</p>
                                            <p>
                                                <span style="color: #0D47A1; font-weight: bold">Palestras: </span>
                                                por acadêmicos, estudantes, profissionais do mercado,
                                                empresas, políticos e pensadores com o intuito de aprofundar
                                                os conhecimentos científicos, técnicos, mercadológicos,
                                                políticos e sociais do Software Livre e da Liberdade do
                                                Conhecimento;
                                            
                                            <p>
                                                <span style="color: #0D47A1; font-weight: bold">Minicursos:
                                                </span> ministrados por profissionais a fim de transmitir
                                                conhecimentos práticos de um determinado assunto por meio de
                                                treinamentos e capacitação;
                                            
                                            <p>
                                                <span style="color: #0D47A1; font-weight: bold">Mesas-redondas/Painéis:
                                                </span> contará com a participação de profissionais e
                                                estudiosos dos temas, qualificados e capacitados para
                                                conduzir as discussões de forma a incentivar o pensamento
                                                crítico dos participantes, visando a estimulação do debate
                                                sobre temas acadêmicos, tecnológicos e sociais relacionados
                                                ao Software Livre e a Liberdade do Conhecimento.
                                            
                                            <p>
                                                <span style="color: #0D47A1; font-weight: bold">Encontro de
                                                    comunidades: </span> comunidades em torno de ferramentas e
                                                tecnologias livre realizam encontros técnicos durante o
                                                evento.
                                        
                                        </span>
                                    </div>
                                </div>
                            </div>
                    
                    </section>




                </div>
            </div>
        </div>
        <div class="right xxs-font">
            <a
                href="https://github.com/ftslorgbr/ftslorgbr.github.io/edit/master/evento.html">aprimore
                esta página &nbsp;</a>
        </div>
    </div>
</section>