<section class="panel grey darken-4">
    <div class="container grey lighten-3" style="height: 64px">
        <div class="row"></div>
    </div>
</section>

<section class="panel grey darken-4">
    <div class="container grey lighten-3" style="padding-bottom: 30px">
        <div class="container">
            <div class="row">
                <div class="sm-font blue-grey-text">
                    <span style="display: inline-block;">Event</span>
                </div>
            </div>
            <div class="row" style="margin-bottom: 0">
                <div>

                    <section class="panel grey lighten-5">
                        <div class="container valign-wrapper">
                            <div class="row">
                                <div class="col">
                                    <div class="left-align lg-padding-v">
                                        <span class="xs-font blue-text text-darken-4">Your event name</span><br> <span
                                            class="xxs-font grey-text text-darken-4">
                                            <p>Talk about your event.</p>
                                            <p>
                                                <span style="color: #0D47A1; font-weight: bold">Talk where it happens.
                                            </p>
                                            <p>Talk about activities:</p>
                                            <p>
                                                <span style="color: #0D47A1; font-weight: bold">Talks, </span>
                                            <p>
                                                <span style="color: #0D47A1; font-weight: bold">Workshops,
                                                </span>
                                            <p>
                                                <span style="color: #0D47A1; font-weight: bold">Meetings
                                                </span>
                                            </p>
                                        </span>
                                    </div>
                                </div>
                            </div>
                    
                    </section>




                </div>
            </div>
        </div>
        <div class="right xxs-font">
            <a
                href="https://github.com/ftslorgbr/ftslorgbr.github.io/edit/master/evento.html">aprimore
                esta página &nbsp;</a>
        </div>
    </div>
</section>