<section class="panel grey darken-4 valign-wrapper"
    style="height: 360px; margin-top: 0px; background-image: url('img/WebHotsiteBg.png');">
    <div class="container">
        <div class="row">
            <div class="col s12 m12 l6 xl6 center-align">
                <div class="md-font flow-text blue-text text-lighten-5 valign">
                    <p class="flow-text">YOUR EVENT NAME</p>
                    <p class="flow-text">start and end
                
                </div>

                <br>
                <div class="center-align">
                    <a href=""
                        class="waves-effect orange waves-light btn">Certified Emission</a>
                </div>
            </div>
            <div class="col s12 m12 l6 xl6 hide-on-med-and-down center-align">
                <div class="md-font white-text valign" style="margin: 0">
                    <p></p>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="panel grey lighten-4 valign-wrapper">
    <div class="container" style="padding: 30px 10px">
        <div class="row">
            <div class="col s4">
                <div class="row">
                    <div class="col s12 center-align">
                        <div class="grey-text text-darken-3">
                            <i class="material-icons medium blue-text text-darken-4">keyboard_voice</i>
                        </div>
                        <span class="sm-font center-align grey-text text-darken-3">Talks</class>
                            <p>
                    
                    </div>
                    <div class="col s12  grey-text text-darken-3">Abstract about talks</div>
                </div>
            </div>
            <div class="col s4">
                <div class="row">
                    <div class="col s12 center-align">
                        <div class="grey-text text-darken-3">
                            <i class="material-icons medium blue-text text-darken-4">watch_later</i>
                        </div>
                        <span class="sm-font center-align grey-text text-darken-3">Workshops</class>
                            <p>
                    
                    </div>
                    <div class="col s12  grey-text text-darken-3">Abstract about workshops</div>
                </div>
            </div>
            <div class="col s4">
                <div class="row">
                    <div class="col s12 center-align">
                        <div class="grey-text text-darken-3">
                            <i class="material-icons medium blue-text text-darken-4">forum</i>
                        </div>
                        <span class="sm-font center-align grey-text text-darken-3">Meetings</class>
                            <p>
                    
                    </div>
                    <div class="col s12  grey-text text-darken-3">Abstract about meetings</div>
                </div>
            </div>
        </div>

        <div class="row hide">
            <div class="col s4">
                <div class="row">
                    <div class="col s12 center-align">
                        <div class="grey-text text-darken-3">
                            <i class="material-icons medium blue-text text-darken-4">brightness_1</i>
                        </div>
                        <span class="sm-font center-align grey-text text-darken-3">Mesas
                            Redondas / Painéis</class>
                            <p>
                    
                    </div>
                    <div class="col s12  grey-text text-darken-3">contará com a
                        participação de profissionais e estudiosos dos temas, qualificados
                        e capacitados para conduzir as discussões de forma a incentivar o
                        pensamento crítico dos participantes, visando a estimulação do
                        debate sobre temas acadêmicos, tecnológicos e sociais relacionados
                        ao Software Livre e a Liberdade do Conhecimento.</div>
                </div>
            </div>

            <div class="col s4">
                <div class="row">
                    <div class="col s12 center-align">
                        <div class="grey-text text-darken-3">
                            <i class="material-icons medium blue-text text-darken-4">memory</i>
                        </div>
                        <span class="sm-font center-align grey-text text-darken-3">Torneio
                            de Robótica</class>
                            <p>
                    
                    </div>
                    <div class="col s12  grey-text text-darken-3"></div>
                </div>
            </div>
            <div class="col s4">
                <div class="row">
                    <div class="col s12 center-align">
                        <div class="grey-text text-darken-3">
                            <i class="material-icons medium blue-text text-darken-4">forum</i>
                        </div>
                        <span class="sm-font center-align grey-text text-darken-3">Encontro
                            de comunidades</class>
                            <p>
                    
                    </div>
                    <div class="col s12  grey-text text-darken-3">comunidades em torno
                        de ferramentas e tecnologias livre realizam encontros técnicos
                        durante o evento.</div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="panel blue darken-4">
    <div class="container valign-wrapper"
        style="height: auto; padding: 20px">
        <div class="center-align">
            <span class="xs-font white-text text-darken-4 flow-text">Join to
                event attendees</span><br> <span
                class="md-font amber-text text-darken-1 flow-text"> in our event</span><br>
            <br> <a class="btn amber darken-4" href="<?=$this->url('public',['action' => 'event'])?>">about event</a>
        </div>

</section>

<section class="panel light-green darken-2">
    <div class="container valign-wrapper"
        style="height: auto; padding: 20px">
        <div class="center-align" style="width: 100%">
            <span class="md-font white-text text-darken-4 flow-text">Don't lose anything!</span><br> <span
                class="xs-font white-text text-darken-1 flow-text">Subscribing our
                newsletter, you know about event news.</span><br>
            <br>
            <div class="center-align" id="mc_embed_signup">
                <form
                    action=""
                    method="post" id="mc-embedded-subscribe-form"
                    name="mc-embedded-subscribe-form" class="validate" target="_blank"
                    novalidate>
                    <div id="mc_embed_signup_scroll">
                        <input type="email" value="" name="EMAIL"
                            class="email dark-blue-text text-darken-4" id="mce-EMAIL"
                            placeholder="endereço de e-mail" required>
                        <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                        <div style="position: absolute; left: -5000px;" aria-hidden="true">
                            <input type="text" name="b_f9f5f09ce1879ee2046ac2e80_12c9acbe55"
                                tabindex="-1" value="">
                        </div>
                        <div class="clear">
                            <input type="submit" value="Subscribe" name="subscribe"
                                id="mc-embedded-subscribe"
                                class="waves-effect lime waves-light btn text-center green-text text-darken-4">
                        </div>
                    </div>
                </form>
            </div>
        </div>

</section>


<section id="guests" class="panel grey darken-4">
    <div class="container grey lighten-4" style="">
        <div class="row ">
            <div class="col s12 sm-font blue-grey-text ">
                <span style="display: inline-block; padding: 10px">Guest speakers<a
                    name="guest"></a></span>
            </div>
        </div>

        <div class="row" style="padding: 0 10px; margin-bottom: 0;"></div>
        <!-- row -->

    </div>
</section>

<section class="panel blue-grey darken-4" id="noticias">
    <div class="container" style="padding: 30px 10px">
        <div class="row"></div>
    </div>
</section>

<section class="panel blue-grey darken-4">
    <div class="green ">
        <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d79533.72907088585!2d-0.021335051080697706!3d51.46863873662521!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47d8a82a8ca9dca7%3A0x31abb25f451c8402!2sObservat%C3%B3rio+Real+de+Greenwich!5e0!3m2!1spt-BR!2sbr!4v1521743400219"
            width="100%" height="500px" frameborder="0 "
            style="border: 0; pointer-events: none;" allowfullscreen
            onfocus="blur()"> </iframe>
    </div>
</section>

<div id="patrocinioFooter"></div>

<section class="panel grey lighten-4">
    <div class="container grey lighten-4">
        <div class="row">
            <div class="col s6 m6 l6" style="padding: 15px">
                <span class="xs-font grey-text text-darken-4 flow-text">Friend Pages</span>
            </div>
            <div class="col s6 m6 l6">
                <span class="xs-font grey-text text-darken-4 flow-text right"><a
                    href="">Join</a></span>
            </div>
        </div>
        <div class="carousel">
            <div class="carousel-item">
                <a href="" target="_blank"><img
                    alt="image of friend page here" height="120"></a>
            </div>
        </div>
    </div>
</section>

<section class="panel grey lighten-4">
    <div class="container grey lighten-4">
        <div class="row">
            <div class="col s6 m6 l6" style="padding: 15px">
                <span class="xs-font grey-text text-darken-4 flow-text">Fellow Event</span>
            </div>
            <div class="col s6 m6 l6">
                <span class="xs-font grey-text text-darken-4 flow-text right"><a
                    href="">Join</a></span>
            </div>
        </div>
        <div class="responsive-img center">
            <a href=""><img alt="image of fellow event here"></a>
        </div>
    </div>
</section>