<section class="panel grey darken-4 valign-wrapper"
    style="height: 360px; margin-top: 0px; background-image: url('img/WebHotsiteBg.png');">
    <div class="container">
        <div class="row">
            <div class="col s12 m12 l6 xl6 center-align">
                <div class="md-font flow-text blue-text text-lighten-5 valign">
                    <p class="flow-text">X FÓRUM DE TECNOLOGIA EM SOFTWARE LIVRE</p>
                    <p class="flow-text">de 27 à 29 de setembro
                
                </div>

                <br>
                <div class="center-align">
                    <a href="https://ftsl.websiteseguro.com/ftsl9/apps/certificados/"
                        class="waves-effect orange waves-light btn">Emissão de
                        Certificados</a>
                </div>
            </div>
            <div class="col s12 m12 l6 xl6 hide-on-med-and-down center-align">
                <div class="md-font white-text valign" style="margin: 0">
                    <p></p>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="panel grey lighten-4 valign-wrapper">
    <div class="container" style="padding: 30px 10px">
        <div class="row">
            <div class="col s4">
                <div class="row">
                    <div class="col s12 center-align">
                        <div class="grey-text text-darken-3">
                            <i class="material-icons medium blue-text text-darken-4">keyboard_voice</i>
                        </div>
                        <span class="sm-font center-align grey-text text-darken-3">Palestras</class>
                            <p>
                    
                    </div>
                    <div class="col s12  grey-text text-darken-3">Realizadas por
                        acadêmicos, estudantes, profissionais do mercado, empresas,
                        políticos e pensadores com o intuito de aprofundar os
                        conhecimentos científicos, técnicos, mercadológicos e sociais do
                        Software Livre e da Liberdade do Conhecimento.</div>
                </div>
            </div>
            <div class="col s4">
                <div class="row">
                    <div class="col s12 center-align">
                        <div class="grey-text text-darken-3">
                            <i class="material-icons medium blue-text text-darken-4">watch_later</i>
                        </div>
                        <span class="sm-font center-align grey-text text-darken-3">Minicursos</class>
                            <p>
                    
                    </div>
                    <div class="col s12  grey-text text-darken-3">Ministrados por
                        profissionais a fim de transmitir conhecimentos práticos de um
                        determinado assunto por meio de treinamentos e capacitação.</div>
                </div>
            </div>
            <div class="col s4">
                <div class="row">
                    <div class="col s12 center-align">
                        <div class="grey-text text-darken-3">
                            <i class="material-icons medium blue-text text-darken-4">forum</i>
                        </div>
                        <span class="sm-font center-align grey-text text-darken-3">Encontro
                            de comunidades</class>
                            <p>
                    
                    </div>
                    <div class="col s12  grey-text text-darken-3">Comunidades em torno
                        de ferramentas e tecnologias livre realizam encontros técnicos
                        durante o evento.</div>
                </div>
            </div>
        </div>

        <div class="row hide">
            <div class="col s4">
                <div class="row">
                    <div class="col s12 center-align">
                        <div class="grey-text text-darken-3">
                            <i class="material-icons medium blue-text text-darken-4">brightness_1</i>
                        </div>
                        <span class="sm-font center-align grey-text text-darken-3">Mesas
                            Redondas / Painéis</class>
                            <p>
                    
                    </div>
                    <div class="col s12  grey-text text-darken-3">contará com a
                        participação de profissionais e estudiosos dos temas, qualificados
                        e capacitados para conduzir as discussões de forma a incentivar o
                        pensamento crítico dos participantes, visando a estimulação do
                        debate sobre temas acadêmicos, tecnológicos e sociais relacionados
                        ao Software Livre e a Liberdade do Conhecimento.</div>
                </div>
            </div>

            <div class="col s4">
                <div class="row">
                    <div class="col s12 center-align">
                        <div class="grey-text text-darken-3">
                            <i class="material-icons medium blue-text text-darken-4">memory</i>
                        </div>
                        <span class="sm-font center-align grey-text text-darken-3">Torneio
                            de Robótica</class>
                            <p>
                    
                    </div>
                    <div class="col s12  grey-text text-darken-3"></div>
                </div>
            </div>
            <div class="col s4">
                <div class="row">
                    <div class="col s12 center-align">
                        <div class="grey-text text-darken-3">
                            <i class="material-icons medium blue-text text-darken-4">forum</i>
                        </div>
                        <span class="sm-font center-align grey-text text-darken-3">Encontro
                            de comunidades</class>
                            <p>
                    
                    </div>
                    <div class="col s12  grey-text text-darken-3">comunidades em torno
                        de ferramentas e tecnologias livre realizam encontros técnicos
                        durante o evento.</div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="panel blue darken-4">
    <div class="container valign-wrapper"
        style="height: auto; padding: 20px">
        <div class="center-align">
            <span class="xs-font white-text text-darken-4 flow-text">Junte-se a
                3000+ participantes</span><br> <span
                class="md-font amber-text text-darken-1 flow-text"> no maior evento
                gratuito de Software Livre do país</span><br>
            <br> <a class="btn amber darken-4" href="evento.html">sobre o evento</a>
        </div>

</section>

<section class="panel light-green darken-2">
    <div class="container valign-wrapper"
        style="height: auto; padding: 20px">
        <div class="center-align" style="width: 100%">
            <span class="md-font white-text text-darken-4 flow-text">Não perca
                nada!</span><br> <span
                class="xs-font white-text text-darken-1 flow-text">Assinando nossa
                newsletter, você fica por dentro das novidades do evento.</span><br>
            <br>
            <div class="center-align" id="mc_embed_signup">
                <form
                    action="//ftsl.us15.list-manage.com/subscribe/post?u=f9f5f09ce1879ee2046ac2e80&amp;id=12c9acbe55"
                    method="post" id="mc-embedded-subscribe-form"
                    name="mc-embedded-subscribe-form" class="validate" target="_blank"
                    novalidate>
                    <div id="mc_embed_signup_scroll">
                        <input type="email" value="" name="EMAIL"
                            class="email dark-blue-text text-darken-4" id="mce-EMAIL"
                            placeholder="endereço de e-mail" required>
                        <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                        <div style="position: absolute; left: -5000px;" aria-hidden="true">
                            <input type="text" name="b_f9f5f09ce1879ee2046ac2e80_12c9acbe55"
                                tabindex="-1" value="">
                        </div>
                        <div class="clear">
                            <input type="submit" value="Assinar" name="subscribe"
                                id="mc-embedded-subscribe"
                                class="waves-effect lime waves-light btn text-center green-text text-darken-4">
                        </div>
                    </div>
                </form>
            </div>
        </div>

</section>


<section id="convidados" class="panel grey darken-4">
    <div class="container grey lighten-4" style="">
        <div class="row ">
            <div class="col s12 sm-font blue-grey-text ">
                <span style="display: inline-block; padding: 10px">Convidados<a
                    name="convidados"></a></span>
            </div>
        </div>

        <div class="row" style="padding: 0 10px; margin-bottom: 0;"></div>
        <!-- row -->

    </div>
</section>

<section class="panel blue-grey darken-4" id="noticias">
    <div class="container" style="padding: 30px 10px">
        <div class="row"></div>
    </div>
</section>

<section class="panel blue-grey darken-4">
    <div class="green ">
        <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d10194.630908771682!2d-49.274705782262856!3d-25.440290915416902!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0000000000000000%3A0x473a188118f5b033!2sUniversidade+Tecnol%C3%B3gica+Federal+do+Paran%C3%A1%2C+Reitoria!5e0!3m2!1spt-BR!2sbr!4v1463079670289"
            width="100%" height="500px" frameborder="0 "
            style="border: 0; pointer-events: none;" allowfullscreen
            onfocus="blur()"> </iframe>
    </div>
</section>

<div id="patrocinioFooter"></div>

<section class="panel grey lighten-4">
    <div class="container grey lighten-4">
        <div class="row">
            <div class="col s6 m6 l6" style="padding: 15px">
                <span class="xs-font grey-text text-darken-4 flow-text">Páginas
                    Amigas</span>
            </div>
            <div class="col s6 m6 l6">
                <span class="xs-font grey-text text-darken-4 flow-text right"><a
                    href="/participar-paginas-amigas.html">participe</a></span>
            </div>
        </div>
        <div class="carousel">
            <div class="carousel-item">
                <a href="http://curitibalivre.org.br/" target="_blank"><img
                    src="img/amigas/logo-curitibalivre300.png" height="120"></a>
            </div>
            <div class="carousel-item">
                <a href="http://phppr.org/" target="_blank"><img
                    src="img/amigas/phppr.png" width="120"></a>
            </div>
            <div class="carousel-item">
                <a href="http://debianbrasil.org.br/" target="_blank"><img
                    src="img/amigas/logo-debian-brasil.png" width="120"></a>
            </div>
            <div class="carousel-item">
                <a href="https://grupypr.github.io/" target="_blank"><img
                    src="img/amigas/grupypr.png" height="120"></a>
            </div>
            <div class="carousel-item">
                <a href="https://www.frameworkdemoiselle.gov.br" target="_blank"><img
                    src="img/amigas/logo-demoiselle.png" height="120"></a>
            </div>

        </div>
    </div>
</section>

<section class="panel grey lighten-4">
    <div class="container grey lighten-4">
        <div class="row">
            <div class="col s6 m6 l6" style="padding: 15px">
                <span class="xs-font grey-text text-darken-4 flow-text">Conferência
                    Irmã</span>
            </div>
            <div class="col s6 m6 l6">
                <span class="xs-font grey-text text-darken-4 flow-text right"><a
                    href="/participar-paginas-amigas.html">participe</a></span>
            </div>
        </div>
        <div class="responsive-img center">
            <a href="http://www.phpconf.com.br"><img src="img/phpconf.png"></a>
        </div>
    </div>
</section>