<section class="panel grey darken-4">
    <div class="container grey lighten-3" style="height: 64px">
        <div class="row"></div>
    </div>
</section>

<section class="panel grey darken-4">
    <div class="container grey lighten-3" style="padding-bottom: 30px">
        <div class="container">
            <div class="row">
                <div class="sm-font blue-grey-text">
                    <span style="display: inline-block;">Política Antiassédio</span>
                </div>
            </div>
            <div class="row" style="margin-bottom: 0">
                <div>
                    <p>O Fórum de Tecnologia em Software Livre (FTSL) está
                        comprometido com uma política antiassédio que visa proporcionar
                        uma experiência livre de assédio para todos e todas as
                        participantes, independentemente de gênero, necessidades
                        especiais, orientação sexual, aparência física, raça, etnicidade,
                        religião e condição sócio-econômica.</p>

                    <p>Nós – membros da organização do FTSL – não toleramos nenhuma
                        forma de assédio ou desrespeito aos participantes do evento.
                        Imagens e linguagem de caráter sexual discriminatório não são
                        apropriadas para o FTSL. Participantes que violarem este código de
                        conduta serão convidados/convidadas a se retirarem do evento.</p>

                    <p>A prática de assédio inclui comentários ofensivos - relacionados
                        com gênero, orientação sexual, aparência física, necessidades
                        especiais, etnicidade, religião e status sócio-econômico- imagens
                        de cunho sexual mostradas em lugares públicos e/ou nas palestras
                        do FTSL, intimidação, perseguição, assédio com câmeras
                        fotográficas e com câmeras de vídeo, repetida interrupção de falas
                        e/ou outros eventos, e contato físico sem consentimento.
                        Participantes cujo comportamento infrinja as regras de conduta do
                        FTSL serão advertidos e devem imediatamente cessar os
                        comportamentos ofensivos, sob o risco de serem convidados a saírem
                        do evento sem a possibilidade de retorno. Os/as organizadores(as)
                        do FTSL tomarão as medidas necessárias para impedir que práticas
                        de assédio aconteçam e/ou sejam repetidas nas palestras do FTSL.</p>

                    <p>Se você se sentiu ameaçado/ameaçada ou
                        desrespeitado/desrespeitada, entre em contato com a organização e
                        exponha as suas preocupações e o ocorrido. Membros da organização
                        do FTSL podem ser identificados através de seus crachás.</p>

                    <p>A organização tomará as medidas necessárias para impedir que as
                        práticas de assédio se repitam. Nós integramos e valorizamos muito
                        a comunidade Software Livre e desejamos a todos um excelente
                        evento, independentemente das diferenças que todos possuímos, que
                        não devem, de forma alguma, nos dividir.</p>

                    <p>
                        Contato: <a href="antiassedio@ftsl.org.br">antiassedio@ftsl.org.br</a>
                    </p>

                    <p>Nós esperamos que todos/as participantes sigam as orientações
                        gerais deste documento e não permitam que práticas sexistas e
                        discriminatórias venham a acontecer no FTSL.</p>

                    <h5 id="licença-e-atribuição">Licença e Atribuição</h5>

                    <p>
                        Esta política está licenciada através da Creative Commons – Brasil
                        - Zero (Domínio Público) e foi baseada na <a
                            href="http://sistema.ftsl.org.br/2014/politica-anti-assedio">política
                            anti-assédio do VI Fórum de Tecnologia em Software Livre (FTSL)</a>,
                        que por sua vez foi paseada na <a
                            href="http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy">política
                            anti-assédio do wiki “Feminist Geek”</a>, criada pela <a
                            href="http://adainitiative.org/">Ada Initiative</a> com a ajuda
                        de várias voluntárias e voluntários.
                    </p>

                    <p>Esta política foi baseada em várias outras políticas
                        antiassédio, incluindo a política da Ohio LinuxFest, escrita por
                        Esther Filderman e Beth Lynn, e a Con Anti-Harassment Project.</p>

                    <p>Mary Gardiner, Valerie Aurora, Sarah Smith, e Donna Benjamin
                        generalizaram as políticas e adicionaram materiais de suporte. A
                        tradução para o português do Brasil foi feita por Luis Felipe
                        Murillo. Membros da LinuxChix, Geek Feminism, bem como outros
                        grupos contribuíram para este trabalho.</p>

                </div>
            </div>
        </div>
        <div class="right xxs-font">
            <a
                href="https://github.com/fgsl/econference/tree/master/module/Publico/view/publico/index/politics.phtml">aprimore
                esta página &nbsp;</a>
        </div>
    </div>
</section>