<a href="<?=$this->url('propriedades',['action'=>'edit'])?>"><?=$this->translate('Add property')?></a>
<table>
<thead>
<tr>
<th><?=$this->translate('Code')?></th>
<th><?=$this->translate('Name')?></th>
<th><?=$this->translate('Edition')?></th>
</tr>
</thead>
<tbody>
<?=$this->partialLoop('propriedades.phtml',$this->propriedades)?>
</tbody>
</table>
<a href="<?=$this->url('application',['action' => 'event-control'])?>"><?=$this->translate('Event Management')?></a>
