<a href="<?=$this->url('edicoes',['action'=>'edit'])?>"><?=$this->translate('Add edition')?></a>
<table>
<thead>
<tr>
<th><?=$this->translate('Code')?></th>
<th><?=$this->translate('Edition')?></th>
<th><?=$this->translate('Hostess')?></th>
<th><?=$this->translate('Finished')?></th>
</tr>
</thead>
<tbody>
<?=$this->partialLoop('edicoes.phtml',$this->edicoes)?>
</tbody>
</table>
<a href="<?=$this->url('application',['action' => 'event-control'])?>"><?=$this->translate('Event Management')?></a>
