<a href="<?=$this->url('anfitrias',['action'=>'edit'])?>"><?=$this->translate('Add hostess')?></a>
<table>
<thead>
<tr>
<th><?=$this->translate('Code')?></th>
<th><?=$this->translate('Name')?></th>
</tr>
</thead>
<tbody>
<?=$this->partialLoop('anfitrias.phtml',$this->anfitrias)?>
</tbody>
</table>
<a href="<?=$this->url('application',['action' => 'event-control'])?>"><?=$this->translate('Event Management')?></a>