<h1><?=$this->translate('Registration of Grids')?></h1>
<form action="<?=$this->url('grades',['action'=>'save'])?>" method="post">
<?=$this->translate('Date')?>:
<input type="text" autofocus="autofocus" name="data" value="<?=$this->grade->data?>">
<br/>
<?=$this->translate('Schedule')?>:
<input type="text" autofocus="autofocus" name="horario" value="<?=$this->grade->horario?>">
<br/>
<select name="codigo_trabalho">
<?=$this->partialLoop('trabalhos_grade.phtml',$this->trabalhos)?>
</select>
<select name="codigo_local">
<?=$this->partialLoop('locais_grade.phtml',$this->locais)?>
</select>
<input type="hidden" value="<?=$this->grade->codigo?>" name="codigo">
<input type="submit" value="<?=$this->translate('save')?>">
</form>
<a href="<?=$this->url('grades')?>"><?=$this->translate('Go back')?></a>
