<a href="<?=$this->url('grades',['action'=>'edit'])?>"><?=$this->translate('Add grid')?></a>
<table>
<thead>
<tr>
<th><?=$this->translate('Code')?></th>
<th><?=$this->translate('Code_Work')?></th>
<th><?=$this->translate('Date')?></th>
<th><?=$this->translate('Schedule')?></th>
<th><?=$this->translate('Code_Places')?></th>
</tr>
</thead>
<tbody>
<?=$this->partialLoop('grades.phtml',$this->grades)?>
</tbody>
</table>
