<?php
use Zend\Authentication\AuthenticationService;
?>
<?=$this->doctype()?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('e-Conference')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/econference.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>                
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
<?php
$authenticationService = new AuthenticationService();
if ($authenticationService->hasIdentity()):
?>
                        <li class="active">Usuário: <?=$authenticationService->getIdentity()?>"></li>
                        <li class="active"><a href="<?= $this->url('home') ?>">Home</a></li>
                        <li class="active"><a href="<?= $this->url('application',['action' => 'access-control']) ?>">Controle de Acesso ao Sistema</a></li>
                        <li class="active"><a href="<?= $this->url('application',['action' => 'event-control']) ?>">Administração do Evento</a></li>
                        <li class="active"><a href="<?= $this->url('application',['action' => 'logout']) ?>">Sair</a></li>                        
<?php
else:
?>
                        <li style="color: white">Sistema de Controle de Conferências</li>
<?php
endif; 
?>                    
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2017 - <?= date('Y') ?> by FTSL. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>