<h1>eConference Installation</h1>
<form action="<?=$this->url('setup',['action' => 'config'])?>" method="post">
<table>
<tr>
<td>Admin user:</td>
<td><input type="text" name="admin_user" autofocus="autofocus"></td>
</tr>
<tr>
<td>Administrator password:</td>
<td><input type="password" name="admin_password"></td>
</tr>
<?php
$drivers = [
    'IbmDb2' => 'IBM DB2',
    'Mysqli' => 'MySQL',
    'Oci8' => 'Oracle',
    'Pgsql' => 'PostgreSQL',
    'Pdo_Mysql' => 'MysQL via PDO',
    'Pdo_Sqlite' => 'SQLite via PDO',
    'Pdo_Pgsql' => 'PostgreSQL via PDO'
] 
?>
<tr>
<td>Database driver:</td>
<td><select name="database_driver">
<?php
foreach ($drivers as $value => $label):
?>
<option value="<?=$value?>" <?=($this->setupConfig['database_driver'] == $value ? 'selected="selected"' : '')?>><?=$label?></option>
<?php    
endforeach;
?>
</select></td>
<tr>
<td>Database server:</td>
<td><input type="text" name="database_host" value="<?=$this->setupConfig['database_host']?>"></td>
</tr>
<tr>
<td>Name of database:</td>
<td><input type="text" name="database_name" value="<?=$this->setupConfig['database_name']?>"></td>
<tr>
<tr>
<td>The database is not created by the application just the tables.<br/>
Created the database before installing the application.</td>
</tr>
<tr>
<td>Database user:</td>
<td><input type="text" name="database_user" value="<?=$this->setupConfig['database_user']?>"></td>
</tr>
<tr>
<td>Database user password:</td>
<td><input type="password" name="database_password" value="<?=$this->setupConfig['database_password']?>"></td>
</tr>
<tr>
<td><input type="submit" value="gravar"></td>
</tr>
</table>
</form>