<a href="<?=$this->url('permissoes',['action'=>'edit'])?>"><?=$this->translate('Add Permission')?></a>
<table>
<thead>
<tr>
<th><?=$this->translate('Code')?></th>
<th><?=$this->translate('Name')?></th>
</tr>
</thead>
<tbody>
<?=$this->partialLoop('permissoes.phtml',$this->permissoes)?>
</tbody>
</table>
<a href="<?=$this->url('application',['action'=>'access-control'])?>"><?=$this->translate('Go back')?></a>
