<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Controle de Acesso ao Sistema</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li><a href="<?= $this->url('perfis') ?>">Perfis</a></li>
                    <li><a href="<?= $this->url('permissoes') ?>">Permissoes</a></li>
                    <li><a href="<?= $this->url('permissoesperfis') ?>">Permissoes de um perfil</a></li>
                    <li><a href="<?= $this->url('usuarios') ?>">Usuarios</a></li>
                </ul>
                <p>
                    <a href="<?= $this->url('home') ?>">Home</a>
                </p>
            </div>
        </div>
    </div>
</div>
