<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?=$this->translate('Event Management')?></h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li class="active"><a href="<?= $this->url('sediadoras')?>"><?=$this->translate('Sediadoras')?></a></li>
                    <li class="active"><a href="<?= $this->url('locais')?>"><?=$this->translate('Places')?></a></li>
                    <li class="active"><a href="<?= $this->url('participantes') ?>"><?=$this->translate('Participants')?></a></li>
                    <li class="active"><a href="<?= $this->url('trabalhos') ?>"><?=$this->translate('Works')?></a></li>
                    <li class="active"><a href="<?= $this->url('categorias') ?>"><?=$this->translate('Categories')?></a></li>
                    <li class="active"><a href="<?= $this->url('grades') ?>"><?=$this->translate('Grids')?></a></li>
                    <li class="active"><a href="<?= $this->url('credenciamentos') ?>"><?=$this->translate('Accreditations')?></a></li>
                </ul>
                <p>
                    <a href="<?= $this->url('home') ?>">Home</a>
                </p>
            </div>
        </div>
    </div>
</div>
