<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Event Management</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li class="active"><a href="<?= $this->url('sediadoras')?>">Sediadoras</a></li>
                    <li class="active"><a href="<?= $this->url('locais')?>">Places</a></li>
                    <li class="active"><a href="<?= $this->url('participantes') ?>">Participants</a></li>
                    <li class="active"><a href="<?= $this->url('trabalhos') ?>">Works</a></li>
                    <li class="active"><a href="<?= $this->url('categorias') ?>">Categories</a></li>
                    <li class="active"><a href="<?= $this->url('grades') ?>">Grids</a></li>
                    <li class="active"><a href="<?= $this->url('credenciamentos') ?>">Accreditations</a></li>
                </ul>
                <p>
                    <a href="<?= $this->url('home') ?>">Home</a>
                </p>
            </div>
        </div>
    </div>
</div>
