<div class="row">
	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Administração do Evento</h3>
			</div>
			<div class="panel-body">
				<ul>
					<li class="active"><a href="<?= $this->url('locais') ?>">Locais</a></li>
					<li class="active"><a href="<?= $this->url('sediadoras')?>">Sediadoras</a></li>
					<li class="active"><a href="<?= $this->url('participantes') ?>">Participantes</a></li>
					<li class="active"><a href="<?= $this->url('trabalhos') ?>">Trabalhos</a></li>
					<li class="active"><a href="<?= $this->url('categorias') ?>">Categorias</a></li>
					<li class="active"><a href="<?= $this->url('grades') ?>">Grades</a></li>
					<li class="active"><a href="<?= $this->url('credenciamentos') ?>">Credenciamentos</a></li>
				</ul>
				<p>
					<a href="<?= $this->url('home') ?>">Home</a>
				</p>
			</div>
		</div>
	</div>
</div>
