<div class="jumbotron">
    <h1><span class="zf-green"><?=$this->translate('Conference Management System')?></span></h1>

    <p>
    <?=$this->translate(
'The conference management system - <i> eConference </i> - aims to 
automate complex tasks in the organization and follow-up of events 
involving lectures and courses.')?>
    </p>

    <p><a class="btn btn-success btn-lg" href="https://github.com/fgsl/econference" target="_blank"><?=$this->translate('Contribute to the project on GitHub')?>&raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?=$this->translate('Content Grid Management')?></h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li><?=$this->translate('Submission of works')?></li> 
                    <li><?=$this->translate('Punctuation and classification of works')?></li>
                    <li><?=$this->translate('Creating tracks according to categories')?></li>
                    <li><?=$this->translate('Time conflict resolution')?></li>
                    <li><?=$this->translate('Connection between work and sponsors')?></li>
                </ul>    
                <p><a class="btn btn-success pull-right" href="#"><?=$this->translate('know more')?></a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?=$this->translate('Management of Activities')?></h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li><?=$this->translate('Task control')?></li>
                    <li><?=$this->translate('Decision making')?></li>
                    <li><?=$this->translate('Revenue and expense control')?></li>
                    <li><?=$this->translate('Audit')?></li>
                </ul>
                <p><a class="btn btn-success pull-right" href="#"><?=$this->translate('know more')?></a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?=$this->translate('Environment')?></h3>
            </div>
            <div class="panel-body">
                <ul>                
                    <li>Apache</li>
                    <li>MySQL</li> 
                    <li>PHP</li>                   
                </ul>            
                <p><a class="btn btn-success pull-right" href="#" target="_blank"><?=$this->translate('know more')?></a></p>
            </div>
        </div>
    </div>
</div>
