<div class="jumbotron">
    <h1><span class="zf-green">Sistema de Gestão de Conferências</span></h1>

    <p>
        O sistema de gestão de conferências - <i>eConference</i> - tem como objetivo
        automatizar as tarefas complexas na organização e acompanhamento de 
        de eventos que envolvam a realização de palestras e cursos.
    </p>

    <p><a class="btn btn-success btn-lg" href="https://github.com/fgsl/econference" target="_blank">Contribua com o projeto no GitHub &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Gestão da Grade de Conteúdo</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li>Submissão de trabalhos</li> 
                    <li>Pontuação e classificação de trabalhos</li>
                    <li>Criação de trilhas de acordo com categorias</li>
                    <li>Resolução de conflito de horários</li>
                    <li>Conexão entre trabalhos e patrocinadores</li>
                </ul>    
                <p><a class="btn btn-success pull-right" href="#">Saiba mais</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Gestão das Atividades</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li>Controle de tarefas</li>
                    <li>Votação de decisões</li>
                    <li>Controle de receita e despesa</li>
                    <li>Auditoria</li>                    
                </ul>
                <p><a class="btn btn-success pull-right" href="#">Saiba mais</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Ambiente</h3>
            </div>
            <div class="panel-body">
                <ul>                
                    <li>Apache</li>
                    <li>MySQL</li> 
                    <li>PHP</li>                   
                </ul>            
                <p><a class="btn btn-success pull-right" href="#" target="_blank">Saiba mais</a></p>
            </div>
        </div>
    </div>
</div>
