<div class="jumbotron">
    <h1><span class="zf-green">Conference Management System</span></h1>

    <p>
        The conference management system - <i> eConference </i> - aims to 
        automate complex tasks in the organization and follow-up of events 
        involving lectures and courses.
    </p>

    <p><a class="btn btn-success btn-lg" href="https://github.com/fgsl/econference" target="_blank">Contribute to the project on GitHub &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Content Grid Management</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li>Submission of works</li> 
                    <li>Punctuation and classification of works</li>
                    <li>Creating tracks according to categories</li>
                    <li>Time conflict resolution</li>
                    <li>Connection between work and sponsors</li>
                </ul>    
                <p><a class="btn btn-success pull-right" href="#">know more</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Management of Activities</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li>Task control</li>
                    <li>Decision making</li>
                    <li>Revenue and expense control</li>
                    <li>Audit</li>                    
                </ul>
                <p><a class="btn btn-success pull-right" href="#">know more</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Environment</h3>
            </div>
            <div class="panel-body">
                <ul>                
                    <li>Apache</li>
                    <li>MySQL</li> 
                    <li>PHP</li>                   
                </ul>            
                <p><a class="btn btn-success pull-right" href="#" target="_blank">know more</a></p>
            </div>
        </div>
    </div>
</div>
